#!/usr/bin/env python3
# encoding: utf-8
# vim: sw=4 ts=4 noexpandtab

from waflib import Logs, Options

def build(bld):
	if 'CC_NAME_SECONDARY' in bld.env or bld.env.CC_NAME != 'msvc':
		if bld.cmd == 'clangdb':
			return
		#endif

		compiler = getattr(bld.env, 'CC_NAME_SECONDARY', bld.env.CC_NAME)

		action = 'building'

		if bld.options.all_tests:
			action = 'running'
		#endif

		Logs.pprint(
			'YELLOW',
			'Skip %s SEH test as %s doesn\'t support SEH properly.'\
				% (action, compiler))
		return
	#endif

	bld.program(
		name='seh_test',
		source=['main.c'],
		target='seh_test',
		cflags=['/EHsc'],
		defines=[],
		includes=['../../LotusCRT/src/include/windows'],
		system_includes=[],
		lib=[],
		libpath=[],
		stlib=[],
		stlibpath=[],
		rpath=[],
		use=['LotusCRT', 'LotusStdC', 'LotusStdC.Memory', 'phnt', 'MSVC'],
		uselib=[],
		features=['test'],
		export_system_includes=[],
		export_defines=[])
#enddef
