#!/usr/bin/env python3
# encoding: utf-8
# vim: sw=4 ts=4 noexpandtab

import sys, os

def build(bld):
	test = bld.program(
		name='gs_test',
		source=['main.c'],
		target='gs_test',
		cflags=['-Wno-array-bounds', '/GS'],
		defines=[],
		includes=[],
		system_includes=[],
		lib=[],
		libpath=[],
		stlib=[],
		stlibpath=[],
		rpath=[],
		use=['LotusCRT', 'LotusStdC', 'LotusStdC.Memory', 'MSVC'],
		uselib=[],
		features=['test'],
		export_system_includes=[],
		export_defines=[])

	test.ut_str = '%(python)s %(script)s --cmd %(cmd)s --expect 3221226505' % {
		'python': sys.executable,
		'script': os.path.abspath('tests/expect_fail.py'),
		'cmd': test.target
	}
#enddef
